CREATE TABLE IF NOT EXISTS lesson_plans (
  plan_id INT PRIMARY KEY AUTO_INCREMENT,
  teacher_id CHAR(9) NOT NULL,
  school_id CHAR(9) NOT NULL,
  class_id INT NOT NULL,
  area_id INT NOT NULL,
  strand_id INT NULL,
  sub_strand_id INT NULL,
  week_number INT NOT NULL DEFAULT 1,
  term VARCHAR(20) NOT NULL DEFAULT 'Term 1',
  lesson_date DATE NULL,
  duration_minutes INT NULL DEFAULT 40,
  learning_objectives TEXT NULL,
  resources TEXT NULL,
  introduction_activities TEXT NULL,
  main_activities TEXT NULL,
  assessment_method TEXT NULL,
  remarks TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (teacher_id) REFERENCES teachers(teacher_id),
  FOREIGN KEY (school_id) REFERENCES schools(school_id),
  FOREIGN KEY (class_id) REFERENCES classes(class_id),
  FOREIGN KEY (area_id) REFERENCES learning_areas(area_id),
  FOREIGN KEY (strand_id) REFERENCES strands(strand_id),
  FOREIGN KEY (sub_strand_id) REFERENCES sub_strands(sub_strand_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
